package hu.bankmonitor.payments.outbox;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.context.annotation.Primary;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.sql.DataSource;
import java.time.Clock;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.function.Consumer;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

/**
 * Every unsent event goes out exactly once per run, and a publish that fails costs its own
 * row and no other.
 *
 * <p>Two criteria live here and they are the same mechanism read in two directions. The
 * happy one — publish, then mark — is what drains the table. The failing one is what makes
 * the design at-<em>least</em>-once rather than at-most-once: the row stays unsent, the rows
 * around it still go out, and the next run picks the failure up. Any implementation that
 * marked first would pass the first of those and quietly lose the event in the second.
 *
 * <p><b>The ordering claim is asserted from inside the publish.</b> A test that only looked
 * at the table afterwards could not tell "published, then marked" from "marked, then
 * published" — both end with a sent row. So the fake reads {@code sent_at} back out of the
 * database while it is holding the event, and finding it null is the assertion.
 *
 * <p>The publisher is a hand-written fake rather than a mock: it collects what it was given
 * and can be told which events it refuses, which is all any assertion here needs. The poller
 * runs by hand, one call per scenario, because "one run" is the unit every claim below is
 * about — and {@code @DataJpaTest} loads no {@code SchedulingConfiguration}, so no scheduled
 * run is racing these.
 *
 * <p>Rows go in as SQL rather than through the recorder, so what is asserted is what reached
 * the database rather than a round trip through the mapping this slice also owns. The
 * identifiers are explicit because the poller's ordering is by identifier, and a test about
 * the order needs to be able to say which row is the older one — the identity column accepts
 * them because it is declared {@code generated by default}.
 */
@DataJpaTest
@Import({OutboxPoller.class, ThePollerPublishesEveryUnsentEventOnceTest.Fixtures.class})
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@TestPropertySource(properties = "spring.jpa.hibernate.ddl-auto=validate")
class ThePollerPublishesEveryUnsentEventOnceTest {

	static final Instant PUBLISHED_AT = Instant.parse("2026-09-05T11:00:00Z");

	private static final Instant OCCURRED_AT = Instant.parse("2026-09-05T10:15:30Z");

	private static final Instant SENT_ON_AN_EARLIER_RUN = Instant.parse("2026-09-05T10:20:00Z");

	private static final long TRANSFER_ID = 77L;

	private static final String EVENT_TYPE = "TRANSFER_SETTLED";

	private static final String PAYLOAD = "{\"transferId\":77}";

	private static final long OLDEST = 1L;

	private static final long MIDDLE = 2L;

	private static final long NEWEST = 3L;

	@Autowired
	private OutboxPoller poller;

	@Autowired
	private RecordingPublisher publisher;

	@Autowired
	private DataSource dataSource;

	private JdbcTemplate jdbc;

	@AfterEach
	void dropEveryEventAndForgetWhatWentOut() {
		jdbc().update("DELETE FROM outbox_events");
		publisher.forgetEverything();
	}

	@Test
	@DisplayName("one run publishes every unsent event oldest first and marks each one sent")
	void oneRunPublishesEveryUnsentEventOldestFirst() {
		unsentEvent(MIDDLE);
		unsentEvent(NEWEST);
		unsentEvent(OLDEST);

		poller.publishUnsentEvents();

		assertThat(publisher.publishedIds()).containsExactly(OLDEST, MIDDLE, NEWEST);
		assertThat(publisher.published).allSatisfy(event -> {
			assertThat(event.getTransferId()).isEqualTo(TRANSFER_ID);
			assertThat(event.getEventType()).isEqualTo(EVENT_TYPE);
			assertThat(event.getPayload()).isEqualTo(PAYLOAD);
		});
		assertThat(sentAtOf(OLDEST)).isEqualTo(PUBLISHED_AT);
		assertThat(sentAtOf(MIDDLE)).isEqualTo(PUBLISHED_AT);
		assertThat(sentAtOf(NEWEST)).isEqualTo(PUBLISHED_AT);
	}

	/**
	 * The timestamp is asserted as well as the absence of a second publish: a poller that
	 * re-marked a sent row would be publishing it again on some run, and the original instant
	 * — the one that says when the news actually left — would be gone.
	 */
	@Test
	@DisplayName("an event another run already published is not published again")
	void anEventAnotherRunAlreadyPublishedIsNotPublishedAgain() {
		eventAlreadySent(OLDEST, SENT_ON_AN_EARLIER_RUN);
		unsentEvent(MIDDLE);

		poller.publishUnsentEvents();

		assertThat(publisher.publishedIds()).containsExactly(MIDDLE);
		assertThat(sentAtOf(OLDEST)).isEqualTo(SENT_ON_AN_EARLIER_RUN);
		assertThat(sentAtOf(MIDDLE)).isEqualTo(PUBLISHED_AT);
	}

	/**
	 * The criterion, in both halves. One undeliverable event does not hold up the ones behind
	 * it — stopping at the first failure would let a single bad row block the table, and there
	 * is no ordering guarantee here for that to be protecting — and the row it left behind is
	 * still unsent, which is the entire retry policy: the next run finds it exactly as the
	 * first one did.
	 */
	@Test
	@DisplayName("a publish failure leaves that row unsent for the next run, and no other")
	void aPublishFailureLeavesThatRowUnsentForTheNextRun() {
		unsentEvent(OLDEST);
		unsentEvent(MIDDLE);
		unsentEvent(NEWEST);
		publisher.refuse(MIDDLE);

		poller.publishUnsentEvents();

		assertThat(publisher.publishedIds()).containsExactly(OLDEST, NEWEST);
		assertThat(sentAtOf(MIDDLE)).isNull();

		publisher.forgetEverything();
		poller.publishUnsentEvents();

		assertThat(publisher.publishedIds()).containsExactly(MIDDLE);
		assertThat(sentAtOf(MIDDLE)).isEqualTo(PUBLISHED_AT);
	}

	/**
	 * Why the order has to be this way round and not the other: marking first would leave a
	 * row claiming an event had gone out whenever the publish that followed it threw, which is
	 * at-most-once delivery wearing an outbox's clothes. The duplicate this order risks
	 * instead is one consumers deduplicate — which they must anyway.
	 */
	@Test
	@DisplayName("an event is published before it is marked, never after")
	void anEventIsPublishedBeforeItIsMarked() {
		unsentEvent(OLDEST);
		unsentEvent(MIDDLE);
		List<Instant> sentAtWhileBeingPublished = new ArrayList<>();
		publisher.whileHoldingEachEvent(event -> sentAtWhileBeingPublished.add(sentAtOf(event.getId())));

		poller.publishUnsentEvents();

		assertThat(sentAtWhileBeingPublished).hasSize(2).containsOnlyNulls();
		assertThat(sentAtOf(OLDEST)).isEqualTo(PUBLISHED_AT);
		assertThat(sentAtOf(MIDDLE)).isEqualTo(PUBLISHED_AT);
	}

	/** Which is every run but a handful, the poller having drained the table a second ago. */
	@Test
	@DisplayName("a run with nothing unsent publishes nothing and complains about nothing")
	void aRunWithNothingUnsentPublishesNothing() {
		eventAlreadySent(OLDEST, SENT_ON_AN_EARLIER_RUN);

		assertThatCode(poller::publishUnsentEvents).doesNotThrowAnyException();

		assertThat(publisher.published).isEmpty();
	}

	private void unsentEvent(long id) {
		jdbc().update("""
				INSERT INTO outbox_events (id, transfer_id, event_type, payload, occurred_at)
				VALUES (?, ?, ?, ?, ?)
				""", id, TRANSFER_ID, EVENT_TYPE, PAYLOAD, atUtc(OCCURRED_AT));
	}

	private void eventAlreadySent(long id, Instant sentAt) {
		jdbc().update("""
				INSERT INTO outbox_events (id, transfer_id, event_type, payload, occurred_at, sent_at)
				VALUES (?, ?, ?, ?, ?, ?)
				""", id, TRANSFER_ID, EVENT_TYPE, PAYLOAD, atUtc(OCCURRED_AT), atUtc(sentAt));
	}

	/** {@code null} while an event is unsent, which is the only thing this column ever says. */
	private Instant sentAtOf(long id) {
		OffsetDateTime sentAt = jdbc().queryForObject(
				"SELECT sent_at FROM outbox_events WHERE id = ?", OffsetDateTime.class, id);
		return sentAt == null ? null : sentAt.toInstant();
	}

	/** H2's {@code timestamp with time zone} takes and returns an {@link OffsetDateTime}. */
	private static OffsetDateTime atUtc(Instant instant) {
		return instant.atOffset(ZoneOffset.UTC);
	}

	/**
	 * Built from the {@link DataSource} rather than injected, on
	 * {@code TheTableDecidesWhoHoldsAKeyTest}'s reasoning: a bean this test asked for would be
	 * one more thing its configuration depends on, and every variation in configuration is
	 * another cached application context (design decision 25).
	 */
	private JdbcTemplate jdbc() {
		if (jdbc == null) {
			jdbc = new JdbcTemplate(dataSource);
		}
		return jdbc;
	}

	/**
	 * A transport that keeps what it was handed and can be told what it will not deliver.
	 *
	 * <p>Its hook runs before the refusal, so a scenario can look at the database at the one
	 * moment that distinguishes publishing from marking — while the poller is inside
	 * {@code publish} and has not returned.
	 */
	static final class RecordingPublisher implements EventPublisher {

		private final List<OutboxEvent> published = new ArrayList<>();

		private final Set<Long> undeliverable = new HashSet<>();

		private Consumer<OutboxEvent> observer = event -> {
		};

		@Override
		public void publish(OutboxEvent event) {
			observer.accept(event);
			if (undeliverable.contains(event.getId())) {
				throw new IllegalStateException("the transport refused event " + event.getId());
			}
			published.add(event);
		}

		List<Long> publishedIds() {
			return published.stream().map(OutboxEvent::getId).toList();
		}

		void refuse(long id) {
			undeliverable.add(id);
		}

		void whileHoldingEachEvent(Consumer<OutboxEvent> observer) {
			this.observer = observer;
		}

		void forgetEverything() {
			published.clear();
			undeliverable.clear();
			observer = event -> {
			};
		}
	}

	/**
	 * The two beans the poller cannot do without and this slice does not otherwise have.
	 *
	 * <p><b>The clock is a second one, deliberately.</b> {@code @DataJpaTest} filters
	 * component scanning but still loads the {@code @SpringBootConfiguration} class itself, so
	 * the application's own {@code systemUTC} {@code @Bean} is already here — a method named
	 * {@code clock()} would be a bean definition override and fail the context outright. A
	 * differently named bean marked {@code @Primary} is what an injection point gets instead,
	 * and it is what makes {@code sent_at} an equality rather than a range.
	 */
	@TestConfiguration
	static class Fixtures {

		@Bean
		@Primary
		Clock fixedClock() {
			return Clock.fixed(PUBLISHED_AT, ZoneOffset.UTC);
		}

		@Bean
		RecordingPublisher publisher() {
			return new RecordingPublisher();
		}
	}
}
