/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/internal/transfers/{transferId}/checks/{check}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reportVerdict"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTransfers"];
        put?: never;
        post: operations["requestTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccounts"];
        put?: never;
        post: operations["openAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["fetchTransfer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VerdictReport: {
            /** @enum {string} */
            verdict: "APPROVED" | "REJECTED";
        };
        VerdictReceipt: {
            /** Format: int64 */
            transferId: number;
            /** @enum {string} */
            check: "FRAUD" | "MANUAL_APPROVAL";
            /** @enum {string} */
            verdict: "APPROVED" | "REJECTED";
            /** @enum {string} */
            transferStatus: "PENDING" | "SETTLED" | "REJECTED" | "EXPIRED";
        };
        CreateTransferRequest: {
            /** Format: int64 */
            fromAccountId: number;
            /** Format: int64 */
            toAccountId: number;
            /** Format: int64 */
            amountMinorUnits: number;
        };
        CheckResponse: {
            /** @enum {string} */
            check: "FRAUD" | "MANUAL_APPROVAL";
            /** @enum {string} */
            verdict?: "APPROVED" | "REJECTED";
        };
        TransferResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            fromAccountId: number;
            /** Format: int64 */
            toAccountId: number;
            /** @enum {string} */
            status: "PENDING" | "SETTLED" | "REJECTED" | "EXPIRED";
            /** Format: int64 */
            debitedAmountMinorUnits: number;
            /** @enum {string} */
            debitedAmountCurrency: "EUR" | "USD" | "HUF";
            /** Format: int64 */
            creditedAmountMinorUnits: number;
            /** @enum {string} */
            creditedAmountCurrency: "EUR" | "USD" | "HUF";
            exchangeRate?: number;
            /** Format: date-time */
            exchangeRateFetchedAt?: string;
            /** Format: date-time */
            createdAt: string;
            checks?: components["schemas"]["CheckResponse"][];
        };
        CreateAccountRequest: {
            /** @enum {string} */
            currency: "EUR" | "USD" | "HUF";
            /** Format: int64 */
            openingBalanceMinorUnits: number;
        };
        AccountResponse: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            currency: "EUR" | "USD" | "HUF";
            /** Format: int64 */
            balanceMinorUnits: number;
            /** Format: int64 */
            reservedAmountMinorUnits: number;
            /** Format: int64 */
            availableBalanceMinorUnits: number;
        };
        /**
         * @description The URN a client branches on, and the only member of the document it may branch on.
         * @enum {string}
         */
        ProblemType: "urn:problem:validation-failed" | "urn:problem:malformed-request" | "urn:problem:unsupported-media-type" | "urn:problem:method-not-allowed" | "urn:problem:not-found" | "urn:problem:forbidden" | "urn:problem:self-transfer" | "urn:problem:unknown-account" | "urn:problem:insufficient-funds" | "urn:problem:conversion-rounds-to-zero" | "urn:problem:check-not-required" | "urn:problem:transfer-not-pending" | "urn:problem:request-in-progress" | "urn:problem:idempotency-key-reused" | "urn:problem:fx-provider-unavailable" | "urn:problem:client-error" | "urn:problem:internal-error";
        /** @description A single rejected value, against the field that carried it. */
        ValidationError: {
            field: string | null;
            message: string;
        };
        /** @description The one shape every failure of this API arrives as. */
        ProblemDocument: {
            type: components["schemas"]["ProblemType"];
            title: string;
            /** Format: int32 */
            status: number;
            detail: string;
            instance: string;
            errors?: components["schemas"]["ValidationError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    reportVerdict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transferId: number;
                check: "FRAUD" | "MANUAL_APPROVAL";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerdictReport"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VerdictReceipt"];
                };
            };
            /** @description A problem document, named by its type URN. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    listTransfers: {
        parameters: {
            query?: {
                status?: "PENDING" | "SETTLED" | "REJECTED" | "EXPIRED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransferResponse"][];
                };
            };
            /** @description A problem document, named by its type URN. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    requestTransfer: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransferRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransferResponse"];
                };
            };
            /** @description A problem document, named by its type URN. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"][];
                };
            };
            /** @description A problem document, named by its type URN. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    openAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
            /** @description A problem document, named by its type URN. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    fetchTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransferResponse"];
                };
            };
            /** @description A problem document, named by its type URN. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
}
