/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccounts"];
        put?: never;
        post: operations["openAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateAccountRequest: {
            /** @enum {string} */
            currency: "EUR" | "USD" | "HUF";
            /** Format: int64 */
            openingBalanceMinorUnits: number;
        };
        AccountResponse: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            currency: "EUR" | "USD" | "HUF";
            /** Format: int64 */
            balanceMinorUnits: number;
            /** Format: int64 */
            reservedAmountMinorUnits: number;
            /** Format: int64 */
            availableBalanceMinorUnits: number;
        };
        /**
         * @description The URN a client branches on, and the only member of the document it may branch on.
         * @enum {string}
         */
        ProblemType: "urn:problem:validation-failed" | "urn:problem:malformed-request" | "urn:problem:unsupported-media-type" | "urn:problem:method-not-allowed" | "urn:problem:not-found" | "urn:problem:request-in-progress" | "urn:problem:idempotency-key-reused" | "urn:problem:fx-provider-unavailable" | "urn:problem:client-error" | "urn:problem:internal-error";
        /** @description A single rejected value, against the field that carried it. */
        ValidationError: {
            field: string | null;
            message: string;
        };
        /** @description The one shape every failure of this API arrives as. */
        ProblemDocument: {
            type: components["schemas"]["ProblemType"];
            title: string;
            /** Format: int32 */
            status: number;
            detail: string;
            instance: string;
            errors?: components["schemas"]["ValidationError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"][];
                };
            };
            /** @description A problem document, named by its type URN. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    openAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
            /** @description A problem document, named by its type URN. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
}
