package hu.bankmonitor.testsupport;

import hu.bankmonitor.payments.common.Currency;
import hu.bankmonitor.payments.common.Money;
import hu.bankmonitor.payments.transfers.TransferStatus;
import hu.bankmonitor.payments.transfers.checks.Check;
import hu.bankmonitor.payments.transfers.checks.Verdict;
import org.jspecify.annotations.Nullable;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;

/**
 * Transfer and Account rows written straight to the tables, for the tests that read
 * Transfers back.
 *
 * <p>Why SQL rather than the application's own path: a Transfer the application can produce
 * is {@code PENDING} and nothing else, because design decision 11 leaves each transition to
 * the ticket that has a caller for it. A test of a listing that reports four statuses cannot
 * be written against a path that reaches one, so the rows are placed rather than made. The
 * same reasoning is recorded in {@code AccountListingTest} for the Available Balance.
 *
 * <p>Static rather than an injected fixture so that a test's {@code @AfterEach} cannot depend
 * on a {@code @BeforeEach} having run first to build it — which is the very ordering trap
 * {@link #startFromTwoAccountsAndNoTransfers} exists to avoid.
 */
public final class TransferRows {

	/** The two Accounts every Transfer written here moves money between. */
	public static final long SOURCE_ACCOUNT = 1L;

	public static final long DESTINATION_ACCOUNT = 2L;

	private TransferRows() {
	}

	/**
	 * Emptied and reopened in one method rather than two: JUnit promises no order between two
	 * {@code @BeforeEach} methods, and opening the Accounts before the delete would leave
	 * every insert that follows without the rows its foreign keys point at.
	 */
	public static void startFromTwoAccountsAndNoTransfers(JdbcTemplate jdbc) {
		empty(jdbc);
		openAccount(jdbc, SOURCE_ACCOUNT, Currency.EUR);
		openAccount(jdbc, DESTINATION_ACCOUNT, Currency.EUR);
	}

	/**
	 * Check Ledger first, then Transfers, then Accounts: each table points at the one below
	 * it, and a foreign key refuses any other order.
	 */
	public static void empty(JdbcTemplate jdbc) {
		jdbc.update("DELETE FROM check_ledger");
		jdbc.update("DELETE FROM transfers");
		jdbc.update("DELETE FROM accounts");
	}

	public static void openAccount(JdbcTemplate jdbc, long id, Currency currency) {
		jdbc.update("""
				INSERT INTO accounts (id, balance_minor_units, balance_currency,
				                      reserved_amount_minor_units, reserved_amount_currency)
				VALUES (?, 1000000, ?, 0, ?)
				""", id, currency.name(), currency.name());
	}

	/**
	 * How much later than the request its rate was quoted, which is the order the application
	 * itself produces: {@code createdAt} is stamped when the request arrives and the quote
	 * comes back from the provider some milliseconds into phase two. A placed row that had
	 * them the other way round would be a row the application cannot write.
	 *
	 * <p>Any positive gap would do; a gap of zero would not, because a row whose two
	 * timestamps agree cannot catch a reader that reports one of them where the other belongs.
	 */
	private static final Duration QUOTED_AFTER_THE_REQUEST = Duration.ofSeconds(2);

	/**
	 * One Transfer with an explicit identifier, which the identity column accepts because it
	 * is declared {@code generated by default}. The identifier has to be given rather than
	 * generated: one endpoint is addressed by it and the listing's order is asserted against
	 * it, and neither can be written against whichever value the sequence had reached.
	 *
	 * <p>The Exchange Rate is filled in exactly when the two sides are denominated
	 * differently, because {@code transfers_rate_iff_cross_currency} refuses both a
	 * cross-Currency row without a rate and a same-Currency row with one. It is derived from
	 * the two amounts rather than passed in, so that a placed row says the same thing the
	 * application's own path would have written and no call site has to name a rate it does
	 * not care about.
	 */
	public static void insertTransfer(JdbcTemplate jdbc, long id, TransferStatus status, Instant createdAt,
			Money debitedAmount, Money creditedAmount) {
		BigDecimal exchangeRate = rateBetween(debitedAmount, creditedAmount);
		jdbc.update("""
				INSERT INTO transfers (id, source_account_id, destination_account_id,
				                       debited_amount_minor_units, debited_amount_currency,
				                       credited_amount_minor_units, credited_amount_currency,
				                       exchange_rate, exchange_rate_fetched_at,
				                       status, created_at)
				VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
				""", id, SOURCE_ACCOUNT, DESTINATION_ACCOUNT,
				debitedAmount.minorUnits(), debitedAmount.currency().name(),
				creditedAmount.minorUnits(), creditedAmount.currency().name(),
				exchangeRate,
				exchangeRate == null ? null
						: createdAt.plus(QUOTED_AFTER_THE_REQUEST).atOffset(ZoneOffset.UTC),
				status.name(), createdAt.atOffset(ZoneOffset.UTC));
	}

	/**
	 * One Check a Transfer requires, in either of the states a ledger row can hold.
	 *
	 * <p>The Verdict is a nullable parameter rather than there being a second method for an
	 * outstanding row, because a null Verdict is how the table itself says nobody has
	 * answered. A test whose claim is that the two are told apart writes them the same way,
	 * so the difference it asserts stays in the argument instead of moving into which method
	 * the fixture happened to call.
	 *
	 * @param verdict what this Check answered, or {@code null} while it is outstanding
	 */
	public static void insertCheck(JdbcTemplate jdbc, long transferId, Check check,
			@Nullable Verdict verdict) {
		jdbc.update("""
				INSERT INTO check_ledger (transfer_id, required_check, verdict)
				VALUES (?, ?, ?)
				""", transferId, check.name(), verdict == null ? null : verdict.name());
	}

	/**
	 * The rate that turns the debited amount into the credited one, which is {@code
	 * CurrencyConversion} read backwards: Minor Units are counted per Currency, so the
	 * difference in decimal places has to come back out before the two figures relate.
	 *
	 * @return {@code null} when both sides share a Currency, which is a Transfer that was
	 *         never quoted rather than one quoted at a rate of one
	 */
	private static @Nullable BigDecimal rateBetween(Money debitedAmount, Money creditedAmount) {
		if (debitedAmount.currency() == creditedAmount.currency()) {
			return null;
		}
		return BigDecimal.valueOf(creditedAmount.minorUnits())
				.movePointRight(debitedAmount.currency().decimalPlaces()
						- creditedAmount.currency().decimalPlaces())
				.divide(BigDecimal.valueOf(debitedAmount.minorUnits()), 10, RoundingMode.HALF_EVEN);
	}
}
