-- Deliberately outside db/migration, which Flyway owns for the real schema: this table
-- belongs to one test and must never reach the application. Column types per design
-- decision 29.
create table money_embedding_host (
    id          bigint generated by default as identity primary key,
    minor_units bigint      not null,
    currency    varchar(3)  not null
);
