/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as TransfersIndexRouteImport } from './routes/transfers/index'
import { Route as TransfersTransferIdRouteImport } from './routes/transfers/$transferId'
import { Route as TransfersNewRouteImport } from './routes/transfers/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIndexRoute = TransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersTransferIdRoute = TransfersTransferIdRouteImport.update({
  id: '/transfers/$transferId',
  path: '/transfers/$transferId',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersNewRoute = TransfersNewRouteImport.update({
  id: '/transfers/new',
  path: '/transfers/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/transfers/$transferId': typeof TransfersTransferIdRoute
  '/transfers/new': typeof TransfersNewRoute
  '/transfers/': typeof TransfersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/transfers/$transferId': typeof TransfersTransferIdRoute
  '/transfers/new': typeof TransfersNewRoute
  '/transfers': typeof TransfersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/transfers/$transferId': typeof TransfersTransferIdRoute
  '/transfers/new': typeof TransfersNewRoute
  '/transfers/': typeof TransfersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/transfers/$transferId'
    | '/transfers/new'
    | '/transfers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/transfers/$transferId'
    | '/transfers/new'
    | '/transfers'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/transfers/$transferId'
    | '/transfers/new'
    | '/transfers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  TransfersTransferIdRoute: typeof TransfersTransferIdRoute
  TransfersNewRoute: typeof TransfersNewRoute
  TransfersIndexRoute: typeof TransfersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/': {
      id: '/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof TransfersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/$transferId': {
      id: '/transfers/$transferId'
      path: '/transfers/$transferId'
      fullPath: '/transfers/$transferId'
      preLoaderRoute: typeof TransfersTransferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/new': {
      id: '/transfers/new'
      path: '/transfers/new'
      fullPath: '/transfers/new'
      preLoaderRoute: typeof TransfersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  TransfersTransferIdRoute: TransfersTransferIdRoute,
  TransfersNewRoute: TransfersNewRoute,
  TransfersIndexRoute: TransfersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
