create table accounts (
    id                          bigint generated by default as identity primary key,

    -- Four columns for two Money embeddables, named by Account's @AttributeOverrides.
    balance_minor_units         bigint     not null,
    balance_currency            varchar(3) not null,
    reserved_amount_minor_units bigint     not null,
    reserved_amount_currency    varchar(3) not null,

    -- Both constraints hold for rows the entity cannot write. Design decision 08.
    constraint accounts_one_currency
        check (balance_currency = reserved_amount_currency),
    constraint accounts_reserved_within_balance
        check (reserved_amount_minor_units between 0 and balance_minor_units)
);
