create table transfers (
    id                          bigint generated by default as identity primary key,

    source_account_id           bigint      not null,
    destination_account_id      bigint      not null,

    -- Four columns for two Money embeddables, named by Transfer's @AttributeOverrides.
    debited_amount_minor_units  bigint      not null,
    debited_amount_currency     varchar(3)  not null,
    credited_amount_minor_units bigint      not null,
    credited_amount_currency    varchar(3)  not null,

    status                      varchar(8)  not null,

    created_at                  timestamp(6) with time zone not null,

    constraint transfers_source_account
        foreign key (source_account_id) references accounts (id),
    constraint transfers_destination_account
        foreign key (destination_account_id) references accounts (id),

    -- All three hold for rows the entity cannot write. See 11-transfer-entity.md.
    -- `= any (array[…])`, never `in (…)` — the README beside this file has why.
    constraint transfers_status_is_known
        check (status = any (array['PENDING', 'SETTLED', 'REJECTED', 'EXPIRED'])),
    constraint transfers_two_distinct_accounts
        check (source_account_id <> destination_account_id),
    constraint transfers_positive_amounts
        check (debited_amount_minor_units > 0 and credited_amount_minor_units > 0)
);
