create table idempotency_records (
    id              bigint generated by default as identity primary key,

    idempotency_key varchar(36) not null,
    payload_hash    varchar(64) not null,

    status          varchar(11) not null,
    response_body   varchar(4000),

    -- The mutual exclusion the whole design rests on: two callers racing the same key
    -- both reach the insert, and the database picks the winner. See 16-idempotent-execution.md.
    constraint idempotency_records_key_is_unique
        unique (idempotency_key),

    -- `= any (array[…])`, never `in (…)` — the README beside this file has why.
    constraint idempotency_records_status_is_known
        check (status = any (array['IN_PROGRESS', 'SUCCEEDED', 'FAILED'])),

    -- A response is what a finished claim has to replay; the two unfinished states
    -- have nothing to say yet.
    constraint idempotency_records_response_only_when_succeeded
        check ((status = 'SUCCEEDED') = (response_body is not null))
);
