create table check_ledger (
    id             bigint generated by default as identity primary key,

    transfer_id    bigint      not null,

    -- `check` is reserved in SQL, so the entity's field is `requiredCheck`. See 19-check-ledger-and-policy.md.
    required_check varchar(15) not null,

    -- Nullable on purpose: no Verdict is how the table says this Check has not answered yet.
    verdict        varchar(8),

    constraint check_ledger_transfer
        foreign key (transfer_id) references transfers (id),

    -- The ledger is fixed when the Transfer is written, not a log of what was reported.
    constraint check_ledger_one_row_per_check
        unique (transfer_id, required_check),

    -- `= any (array[…])`, never `in (…)` — the README beside this file has why.
    constraint check_ledger_check_is_known
        check (required_check = any (array['FRAUD', 'MANUAL_APPROVAL'])),
    constraint check_ledger_verdict_is_known
        check (verdict is null or verdict = any (array['APPROVED', 'REJECTED']))
);
