create table outbox_events (
    id          bigint       generated by default as identity primary key,

    -- An identifier and not a foreign key. Every other table that points at `transfers`
    -- sits inside it; this one is the slice `transfers` depends on, and a constraint here
    -- would be the outbox pointing back. See 27-outbox-and-poller.md.
    transfer_id bigint        not null,

    -- No `check` listing the known types: the outbox carries a vocabulary it does not own,
    -- and a constraint would make every new event type an edit to this slice.
    event_type  varchar(40)   not null,

    -- Fat on purpose. A consumer that had to call back for the amount is the coupling
    -- design decision 11 rejected polling to avoid.
    payload     varchar(4000) not null,

    occurred_at timestamp(6) with time zone not null,

    -- Null is how this table says an event has not been published yet. It is the poller's
    -- whole predicate, and the reason for the index below.
    sent_at     timestamp(6) with time zone
);

-- The poller reads `sent_at is null order by id`. H2 has no partial index, so the sent
-- rows are carried in this one rather than excluded from it; leading with `sent_at` still
-- groups the unsent ones, and trailing with `id` gives the ordering for free.
create index outbox_events_unsent on outbox_events (sent_at, id);
