package hu.bankmonitor.payments.transfers;

import hu.bankmonitor.payments.common.Currency;
import hu.bankmonitor.payments.transfers.checks.Check;
import hu.bankmonitor.testsupport.BootedApplicationTest;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * The Accounts, the reads and the cleanup every test of a Transfer's life shares — the
 * reservation that opens one and the Verdict that closes it.
 *
 * <p><b>Nothing here is transactional, and that is the point.</b> A {@code @Transactional}
 * test method makes every write it performs invisible to any other connection and rolls the
 * lot back at the end — which would leave
 * {@link ConcurrentReservationsHoldTheBalanceTest}'s second thread unable to see the first
 * thread's reservation, and every assertion in
 * {@link ReservedFundsReachTheTableTest} agreeing with a transaction that never committed.
 * Every subclass needs real commits, so the price is paying for the cleanup by hand.
 *
 * <p>The tables are emptied before each method as well as after: one in-memory H2 database is
 * shared by every test in the suite, whichever application context booted it, and the
 * assertions below count rows rather than looking only at their own.
 *
 * <p>Rows go in and come back out in SQL rather than through the entities, so what is
 * asserted is what reached the database — a round trip through the mapping under test would
 * agree with itself whatever it wrote.
 */
abstract class TransferScenario extends BootedApplicationTest {

	static final Instant REQUESTED_AT = Instant.parse("2026-09-05T10:15:30Z");

	@Autowired
	FundsReservation reservation;

	@Autowired
	VerdictRecording verdicts;

	@Autowired
	JdbcTemplate database;

	/**
	 * Ledger first, then Transfers, then Accounts: each table points at the one below it.
	 * Claims come last and in any order — no foreign key reaches an Idempotency Key, which
	 * is the point of design decision 3 putting the claim above the work rather than beside
	 * it.
	 *
	 * <p>The claims are emptied here rather than by the two subclasses that request
	 * Transfers over HTTP, because a key left behind outlives the test that made it: it is
	 * committed by design, so the next test to use the same key would be answered by the
	 * previous test's claim instead of making one.
	 */
	@BeforeEach
	@AfterEach
	void emptyTheLedgerTransferAccountAndClaimTables() {
		database.update("DELETE FROM check_ledger");
		database.update("DELETE FROM transfers");
		database.update("DELETE FROM accounts");
		database.update("DELETE FROM idempotency_records");
	}

	/**
	 * With an explicit identifier, which the identity column accepts because it is declared
	 * {@code generated by default}. The lock order is ascending by ID, so a test about two
	 * Accounts needs to be able to say which of them is the lower one.
	 */
	void openAccount(long id, long balanceMinorUnits, Currency currency) {
		database.update("""
				INSERT INTO accounts (id, balance_minor_units, balance_currency,
				                      reserved_amount_minor_units, reserved_amount_currency)
				VALUES (?, ?, ?, 0, ?)
				""", id, balanceMinorUnits, currency.name(), currency.name());
	}

	/**
	 * Reads as the sentence a Transfer is — an amount, out of one Account, into another —
	 * which is deliberately not the order {@link ReservationRequest} declares its components
	 * in. Three adjacent {@code long}s are swappable in silence either way; naming the two
	 * Accounts {@code from} and {@code to} is what makes a swapped call read wrong.
	 */
	static ReservationRequest transferOf(long amountMinorUnits, long fromAccountId, long toAccountId) {
		return new ReservationRequest(fromAccountId, toAccountId, amountMinorUnits, REQUESTED_AT);
	}

	long balanceOf(long accountId) {
		return minorUnitsOf("balance_minor_units", accountId);
	}

	long reservedAmountOf(long accountId) {
		return minorUnitsOf("reserved_amount_minor_units", accountId);
	}

	/** What an overdraft check tests against, read back from the two columns it is derived from. */
	long availableBalanceOf(long accountId) {
		return balanceOf(accountId) - reservedAmountOf(accountId);
	}

	List<Map<String, Object>> transferRows() {
		return database.queryForList("SELECT * FROM transfers ORDER BY id");
	}

	List<Map<String, Object>> checkLedgerRows() {
		return database.queryForList("SELECT * FROM check_ledger ORDER BY id");
	}

	/** The status the column holds, as the string it holds it as. */
	String statusOf(long transferId) {
		return database.queryForObject(
				"SELECT status FROM transfers WHERE id = ?", String.class, transferId);
	}

	/** How far the claim on an Idempotency Key has got, as the string the column holds it as. */
	String claimedStatus(String idempotencyKey) {
		return database.queryForObject(
				"SELECT status FROM idempotency_records WHERE idempotency_key = ?",
				String.class, idempotencyKey);
	}

	/** How one Check has been answered for one Transfer, {@code null} while it is outstanding. */
	String verdictOn(long transferId, Check check) {
		return database.queryForObject(
				"SELECT verdict FROM check_ledger WHERE transfer_id = ? AND required_check = ?",
				String.class, transferId, check.name());
	}

	private long minorUnitsOf(String column, long accountId) {
		Long minorUnits = database.queryForObject(
				"SELECT " + column + " FROM accounts WHERE id = ?", Long.class, accountId);
		return minorUnits == null ? 0L : minorUnits;
	}
}
